/**
 * @module enums
 * @description All the enums used in the project grouped in a single module to prevent circular dependencies between modules.
 * */

/** Named breakpoints of the execution. These steps have a textual description displayed in the step description
 * box UI element and a text to speech sentence associated to them.
 * If the {@link Execution} {@link StepMode|stepping mode} is set to {@link StepMode.STEP}, every time the end
 * of the step is signaled the execution is paused */
export enum ExecutionStep {
	PROGRAM_COUNTER_TO_ADDRESS_BUS,
	MEMORY_TO_INSTRUCTION_REGISTER,
	DECODE_OPCODE,
	INVALID_OPCODE,
	NO_OP,
	HALT,
	SET_ADDRESSING_MODE,
	SET_ALU_OPERATION,
	LOAD_OPERAND_1_FROM_ACCUMULATOR,
	INCREMENT_PROGRAM_COUNTER,
	LOAD_IMMEDIATE_OPERAND,
	DIRECT_OPERAND_TO_ADDRESS_BUS,
	SIGNAL_MEMORY_FETCH,
	SIGNAL_MEMORY_READ,
	SIGNAL_MEMORY_WRITE,
	LOAD_OPERAND_2_FROM_MEMORY,
	SET_PROGRAM_COUNTER_TO_DIRECT_OPERAND,
	EXECUTE_OPERATION,
	UPDATE_STATUS_WORD,
	ACCUMULATOR_TO_DATA_BUS,
	ACCUMULATOR_STORED_TO_MEMORY,
}

/** The stage of the {@link Execution} */
export enum ExecutionStage {
	FETCH,
	DECODE,
	EXECUTE,
	INCREMENT_PROGRAM_COUNTER,
}

/** Identifier of an UI element */
export enum UI {
	// CPU
	PROGRAM_COUNTER,
	PROGRAM_COUNTER_INCREMENT,
	INSTRUCTION_REGISTER,
	INSTRUCTION_REGISTER_OPERAND,
	INSTRUCTION_REGISTER_OPCODE,
	DECODER,
	CONTROL_UNIT,
	MUX,
	ALU_OPERAND_1,
	ALU_OPERAND_2,
	ALU_OPERATION,
	ACCUMULATOR,
	STATUS_WORD,
	STATUS_WORD_ZERO_FLAG,
	STATUS_WORD_NEGATIVE_FLAG,
	// Memory
	MEMORY_SELECTED_ADDRESS,
	MEMORY_SELECTED_DATA,
	// Labels
	LABEL,
	// Control bar
	CONTROL_BAR,
	// Program execution
	PROGRAM_EXECUTION_BUTTON_GROUP,
	RESET_EXECUTION_BUTTON,
	TOGGLE_PROGRAM_EXECUTION_BUTTON,
	FAST_PROGRAM_EXECUTION_BUTTON,
	// Instruction execution
	INSTRUCTION_EXECUTION_BUTTON_GROUP,
	TOGGLE_INSTRUCTION_EXECUTION_BUTTON,
	FAST_INSTRUCTION_EXECUTION_BUTTON,
	// Step execution
	STEP_EXECUTION_BUTTON_GROUP,
	TOGGLE_STEP_EXECUTION_BUTTON,
	FAST_STEP_EXECUTION_BUTTON,
	// Execution speed
	EXECUTION_SPEED_SLIDER,
	// Binary mode toggle
	BINARY_MODE_TOGGLE,
	// Animations toggle
	ANIMATIONS_TOGGLE,
}

/** Source or destination for a read/write {@link Bus} operation */
export enum Register {
	// CPU
	PROGRAM_COUNTER,
	INSTRUCTION_REGISTER,
	INSTRUCTION_REGISTER_OPCODE,
	INSTRUCTION_REGISTER_OPERAND,
	DECODER,
	CONTROL_UNIT,
	MUX,
	ALU_OPERAND_1,
	ALU_OPERAND_2,
	ALU_OPERATION,
	ALU_RESULT,
	ALU_STATUS_WORD,
	ACCUMULATOR,
	STATUS_WORD,
	// Memory
	MEMORY_ADDRESS,
	MEMORY_OPERATION,
	MEMORY_DATA,
}

/** ID of a {@link Bus} */
export enum BusID {
	DATA,
	ADDRESS,
	MEMORY_CONTROL,
	OPCODE_DECODER,
	MUX_ALU,
	MUX_CONTROL,
	ALU_CONTROL,
	STATUS_WORD,
	ALU_ACCUMULATOR,
}

/** Identifier of the type of an {@link Action}.
 * Note: the code relies for this to be a numeric enum, don't change it into a string enum. */
export enum ActionType {
	// Execution
	HALT_EXECUTION,
	SET_EXECUTION_STEP,
	END_EXECUTION_STEP,
	TRANSITION_EXECUTION_STAGE,
	// Bus
	SEND_SIGNAL,
	END_SIGNAL,
	READ_SIGNAL,
	// Cpu
	DECODE_OPCODE,
	EXECUTE_OPCODE,
	EXECUTE_ALU_OPERATION,
	SET_MEMORY_OPERATION,
	INCREMENT_PROGRAM_COUNTER,
	// Text-to-speech
	TEXT_TO_SPEECH_READ,
	TEXT_TO_SPEECH_READ_LOCALIZED,
	TEXT_TO_SPEECH_READ_EXECUTION_STEP,
	WAIT_TEXT_TO_SPEECH_FINISH,
	// Notifications
	SEND_NOTIFICATION,
	// Animations
	FLASH_UI_ELEMENT,
	WAIT_UI_ELEMENT_ANIMATION,
	CANCEL_UI_ELEMENT_ANIMATION,
	FLASH_WIRE,
	WAIT_WIRE_ANIMATION,
	CANCEL_WIRE_ANIMATION,
}
