/** Source or destination for a read/write {@link Bus} operation */
export enum RegisterID {
	// CPU
	PROGRAM_COUNTER,
	PROGRAM_COUNTER_INCREMENTER,
	INSTRUCTION_REGISTER,
	INSTRUCTION_REGISTER_OPCODE,
	INSTRUCTION_REGISTER_OPERAND,
	DECODER_INPUT,
	DECODER_OUTPUT,
	CONTROL_UNIT_ADDRESSING_MODE,
	CONTROL_UNIT_MEMORY_OPERATION,
	MUX_SIGNAL,
	MUX_ADDRESSING_MODE,
	ALU_OPERAND_1,
	ALU_OPERAND_2,
	ALU_OPERATION,
	ALU_RESULT,
	ALU_STATUS_WORD,
	ACCUMULATOR,
	STATUS_WORD,
	// Memory
	MEMORY_ADDRESS,
	MEMORY_OPERATION,
	MEMORY_DATA,
}

/** ID of a {@link Bus} */
export enum BusID {
	DATA,
	ADDRESS,
	MEMORY_CONTROL,
	OPCODE_DECODER,
	MUX_ALU,
	MUX_CONTROL,
	ALU_CONTROL,
	STATUS_WORD,
	ALU_ACCUMULATOR,
}
