# https://github.com/marketplace/actions/deploy-to-github-pages
name: Build and Deploy
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: 
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and Build
        run: |
          find .
          npm install 
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: page
          folder: public
      - name: Push to cpuvisualsimulator/cpuvisualsimulator.github.io/main
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: public
          destination-github-username: cpuvisualsimulator
          destination-repository-name: cpuvisualsimulator.github.io
          target-branch: main